name: Create Order Issue

on:
  repository_dispatch:
    types: [new-order]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const payload = context.payload.client_payload
            const issueTitle = `سفارش ${payload.product} از ${payload.username}`
            const issueBody = `**کاربر:** ${payload.username}\n**محصول:** ${payload.product}\n**قیمت:** ${payload.price}`
            await github.rest.issues.create({
              owner: "KingRT-site",
              repo: "orders-db",
              title: issueTitle,
              body: issueBody,
              labels: ["order"]
            })

